package org.terifan.bundle;


enum FieldType2
{
	BOOLEAN,
	BYTE,
	SHORT,
	CHAR,
	INT,
	LONG,
	FLOAT,
	DOUBLE,
	STRING,
	BUNDLE,
	DATE,
	@Deprecated unused_1_1,
	@Deprecated unused_1_2,
	@Deprecated unused_1_3,
	@Deprecated unused_1_4,
	@Deprecated unused_1_5,

	BOOLEAN_ARRAY,
	BYTE_ARRAY,
	SHORT_ARRAY,
	CHAR_ARRAY,
	INT_ARRAY,
	LONG_ARRAY,
	FLOAT_ARRAY,
	DOUBLE_ARRAY,
	STRING_ARRAY,
	BUNDLE_ARRAY,
	DATE_ARRAY,
	@Deprecated unused_2_1,
	@Deprecated unused_2_2,
	@Deprecated unused_2_3,
	@Deprecated unused_2_4,
	@Deprecated unused_2_5,

	BOOLEAN_MATRIX,
	BYTE_MATRIX,
	SHORT_MATRIX,
	CHAR_MATRIX,
	INT_MATRIX,
	LONG_MATRIX,
	FLOAT_MATRIX,
	DOUBLE_MATRIX,
	STRING_MATRIX,
	BUNDLE_MATRIX,
	DATE_MATRIX,
	@Deprecated unused_3_1,
	@Deprecated unused_3_2,
	@Deprecated unused_3_3,
	@Deprecated unused_3_4,
	@Deprecated unused_3_5,

	BOOLEAN_ARRAYLIST,
	BYTE_ARRAYLIST,
	SHORT_ARRAYLIST,
	CHAR_ARRAYLIST,
	INT_ARRAYLIST,
	LONG_ARRAYLIST,
	FLOAT_ARRAYLIST,
	DOUBLE_ARRAYLIST,
	STRING_ARRAYLIST,
	BUNDLE_ARRAYLIST,
	DATE_ARRAYLIST,
	@Deprecated unused_4_1,
	@Deprecated unused_4_2,
	@Deprecated unused_4_3,
	@Deprecated unused_4_4,
	@Deprecated unused_4_5
}